version: "3"
services:
  strapi:
    image: strapi/strapi
    env_file: ./env/strapi.env
    volumes:
      - ./data/strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file: ./env/postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
